main: main.c list.h list.c util.h util.c
	clear;
	gcc -o main main.c list.h list.c util.h util.c


debug: main.c list.h list.c util.h util.c
	clear;
	gcc -g main.c list.h list.c util.h util.c
	gdb a.out

clean:
	rm main
